### ISSUE TITLE
Error not in sync with the name pattern

### ISSUE THREAD

**Issue by shobsi** [twistedpair/google-cloud-sdk#9]
The error on function name pattern says only hyphen (`-`) is acceptable

https://github.com/twistedpair/google-cloud-sdk/blob/23a3ae5621dc114ebc6ab5d7981f0c3ac3d590c5/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/v1/util.py#L57

but the regex itself allos underscore `(_)`

https://github.com/twistedpair/google-cloud-sdk/blob/23a3ae5621dc114ebc6ab5d7981f0c3ac3d590c5/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/v1/util.py#L53

**Comment by twistedpair** [comment]
This is a mirror repo. It is not the location for reporting gcloud bugs.

To report gcloud bugs, please see the [official bug tracker](https://issuetracker.google.com/issues/new?component=187143&pli=1&template=800102).
